[inputs.nixpkgs]
url = "github:NixOS/nixpkgs/nixpkgs-unstable"

[inputs.swash]
url = "github:ItsLemmy/swash"
follows = { nixpkgs = "nixpkgs" }

[inputs.home-manager]
url = "github:nix-community/home-manager"
follows = { nixpkgs = "nixpkgs" }
