color0 #fcdbdb
color1 #ba1a1a
color2 #a22d3b
color3 #8a4d4f
color4 #844a00
color5 #a46063
color6 #a46063
color7 #241919
color8 #8b7171
color9 #ba1a1a
color10 #a22d3b
color11 #8a4d4f
color12 #844a00
color13 #a46063
color14 #a46063
color15 #241919

cursor                #241919
cursor_text_color     #fff8f7
background            #fff8f7
foreground            #241919
selection_foreground  #574142
selection_background  #fcdbdb
active_border_color   #a22d3b
inactive_border_color #fcdbdb
url_color             #a22d3b

active_tab_foreground   #ffffff
active_tab_background   #a22d3b
inactive_tab_foreground #574142
inactive_tab_background #fcdbdb
cursor_trail_color      #574142
