color0 #4a4456
color1 #ffb4ab
color2 #d1bcff
color3 #d1bcff
color4 #fface8
color5 #d1bcff
color6 #d1bcff
color7 #e7dfef
color8 #958da2
color9 #ffb4ab
color10 #d1bcff
color11 #d1bcff
color12 #fface8
color13 #d1bcff
color14 #d1bcff
color15 #e7dfef

cursor                #e7dfef
cursor_text_color     #15121c
background            #15121c
foreground            #e7dfef
selection_foreground  #ccc3d9
selection_background  #4a4456
active_border_color   #d1bcff
inactive_border_color #4a4456
url_color             #d1bcff

active_tab_foreground   #3d0090
active_tab_background   #d1bcff
inactive_tab_foreground #ccc3d9
inactive_tab_background #4a4456
cursor_trail_color      #ccc3d9
