color0 #43474e
color1 #ffb4ab
color2 #a1cafd
color3 #bbc7db
color4 #d7bee4
color5 #a1cafd
color6 #bbc7db
color7 #e1e2e8
color8 #8d9199
color9 #ffb4ab
color10 #a1cafd
color11 #bbc7db
color12 #d7bee4
color13 #a1cafd
color14 #bbc7db
color15 #e1e2e8

cursor                #e1e2e8
cursor_text_color     #111418
background            #111418
foreground            #e1e2e8
selection_foreground  #c3c6cf
selection_background  #43474e
active_border_color   #a1cafd
inactive_border_color #43474e
url_color             #a1cafd

active_tab_foreground   #003259
active_tab_background   #a1cafd
inactive_tab_foreground #c3c6cf
inactive_tab_background #43474e
cursor_trail_color      #c3c6cf
