color0 #46464e
color1 #ffb4ab
color2 #c1c3f3
color3 #c5c5da
color4 #ecb7d9
color5 #c1c3f3
color6 #c5c5da
color7 #e5e1e5
color8 #919099
color9 #ffb4ab
color10 #c1c3f3
color11 #c5c5da
color12 #ecb7d9
color13 #c1c3f3
color14 #c5c5da
color15 #e5e1e5

cursor                #e5e1e5
cursor_text_color     #131316
background            #131316
foreground            #e5e1e5
selection_foreground  #c7c5cf
selection_background  #46464e
active_border_color   #c1c3f3
inactive_border_color #46464e
url_color             #c1c3f3

active_tab_foreground   #2a2d54
active_tab_background   #c1c3f3
inactive_tab_foreground #c7c5cf
inactive_tab_background #46464e
cursor_trail_color      #c7c5cf
