color0 #4d4639
color1 #ffb4ab
color2 #e9c16c
color3 #d8c4a0
color4 #b0cfa9
color5 #e9c16c
color6 #d8c4a0
color7 #ebe1d4
color8 #998f80
color9 #ffb4ab
color10 #e9c16c
color11 #d8c4a0
color12 #b0cfa9
color13 #e9c16c
color14 #d8c4a0
color15 #ebe1d4

cursor                #ebe1d4
cursor_text_color     #17130b
background            #17130b
foreground            #ebe1d4
selection_foreground  #d0c5b4
selection_background  #4d4639
active_border_color   #e9c16c
inactive_border_color #4d4639
url_color             #e9c16c

active_tab_foreground   #402d00
active_tab_background   #e9c16c
inactive_tab_foreground #d0c5b4
inactive_tab_background #4d4639
cursor_trail_color      #d0c5b4
